version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - "9216:9215"
    depends_on:
      - postgresql_db
    command: sh -c './wait-for postgresql_db:5432 -- npm start'
  postgresql_db:
    image: "postgres:14"
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: app_test_db
      POSTGRES_USER: user_giash
      POSTGRES_PASSWORD: nE5kMc7JCGNqwDQM
volumes:
  postgres_db_data:
